- file: path=~/.secrets state=directory mode=700
  sudo_user: dschep
- include_vars: "pushover_tokens.yml"
- include_vars: "pushbullet_token.yml"
- name: Copy Pushover secrets
  sudo_user: dschep
  copy:
    dest: ~/.secrets/pushover
    content: |
       PUSHOVER_APP_TOKEN={{ PUSHOVER_APP_TOKEN }}
       PUSHOVER_USER_TOKEN={{ PUSHOVER_USER_TOKEN }}
- name: Copy Pushbullet secrets
  sudo_user: dschep
  copy:
    dest: ~/.secrets/pushbullet
    content: PUSHBULLET_TOKEN={{ PUSHBULLET_TOKEN }}
- name: Install ntfy config
  sudo_user: dschep
  template: src=ntfy.json dest=~/.ntfy.json
