- file: path=~/.secrets state=directory
  sudo_user: dschep
- include_vars: "pushover_tokens.yml"
- name: Copy Pushover secrets
  sudo_user: dschep
  copy:
    dest: ~/.secrets/pushover
    content: |
       PUSHOVER_APP_TOKEN={{ PUSHOVER_APP_TOKEN }}
       PUSHOVER_USER_TOKEN={{ PUSHOVER_USER_TOKEN }}
