- name: "Download hub"
  unarchive:
    src: https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz
    dest: /opt/
    remote_src: True
    creates: hub-linux-amd64-2.2.9

- name: "link hub"
  file:
    src: /opt/hub-linux-amd64-2.2.9/bin/hub
    dest: /usr/bin/hub
    state: link

