- name: ensure user font dir
  become_user: "{{ user }}"
  file: path=~/.fonts state=directory

- name: install Hack font
  become_user: "{{ user }}"
  copy: src=fonts/{{ item }} dest=~/.fonts/{{ item }}
  with_items:
    - Hack-BoldOblique.otf
    - Hack-Bold.otf
    - Hack-RegularOblique.otf
    - Hack-Regular.otf
  notify:
    - rebuild font cache
