---
#- hosts: all
  #roles:
    #- base_utils
    #- dotfiles

- hosts: atlas
  become: yes
    #  roles:
    #    - docker
    #    - portainer
    #    - netdata
  tasks:
    #- apt: deb=https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    #- apt: pkg=nmap
    #- apt: pkg=golang-go
    #- apt: pkg=gopls
      #- apt: pkg=python3-pip
      #- apt: pkg=nfs-common
      #- apt: pkg=pyosmium
    - apt: deb=https://downloads.rclone.org/v1.64.0/rclone-v1.64.0-linux-amd64.deb
      #- pip: name=git+https://github.com/dschep/ntfy
