
---
- hosts: 005465.local # work mac
  become: no
  roles:
    - fnm
  tasks:
    - homebrew_cask: name={{ item }}
      with_items:
        #- google-chrome # preinstalled
        #- firefox
        - ghostty
        #- bettertouchtool
        - meld
        - google-cloud-sdk
        - dbeaver-community
        - inkscape
        - gimp
        - mark-text
        #- virtualbox
    - homebrew: name={{ item }}
      with_items:
        - socat
        - htop
        - httpie
        - jq
        - qgis
        - gdal
        - tippecanoe
    #- name: install ntfy
    #  become: yes
    #  community.general.pipx:
    #    name: ntfy
