---
- hosts: potassium
  become: yes
  roles:
    - base
    - openbox
    - atkinson_hyperlegible
    - alacritty
- hosts: potassium
  become: yes
  tasks:
    - name: symlink x-terminal-emulator to alacritty # because arch doesn't do alternates i guess?
      ansible.builtin.file:
        src: /usr/bin/alacritty
        dest: /usr/bin/x-terminal-emulator
        state: link
    - package: name={{ item }}
      with_items:
        - gimp
        - inkscape
        - gimp
        - firefox
    - package: name={{ item }}
        - nvm
