---
- hosts: potassium
  become: yes
  roles:
    - dotfiles
    #- base_utils # not directly using bc vim vs gvim
    - atkinson_hyperlegible
    - alacritty
    - fnm # needed to make .local/bin
    #- kde
- hosts: potassium
  become: yes
  tasks:
    - name: Configure apt sources
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: |
          deb http://deb.debian.org/debian/ trixie main non-free-firmware contrib non-free
          deb-src http://deb.debian.org/debian/ trixie main non-free-firmware contrib non-free
          deb http://security.debian.org/debian-security trixie-security main non-free-firmware contrib non-free
          deb-src http://security.debian.org/debian-security trixie-security main non-free-firmware contrib non-free
          deb http://deb.debian.org/debian/ trixie-updates main non-free-firmware contrib non-free
          deb-src http://deb.debian.org/debian/ trixie-updates main non-free-firmware contrib non-fre
        owner: root
        group: root
        mode: '0644'
      register: sources_file
    - name: Configure Debian Trixie backports
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/debian-backports.sources
        content: |
          Types: deb deb-src
          URIs: http://deb.debian.org/debian
          Suites: trixie-backports
          Components: main
          Enabled: yes
          Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg
        owner: root
        group: root
        mode: '0644'
      register: backports_file
    - name: Update APT cache if sources file changed
      ansible.builtin.apt:
        update_cache: yes
      when: sources_file.changed or backports_file.changed

    - package: name={{ item }}
      with_items:
        - gimp
        - inkscape
        - gimp
        - firefox-esr
        - just
        - httpie
        #- docker
        - ripgrep
        - wl-clipboard
        - chromium
        - meld
        - aria2
        - vlc
        # base_utils (but s/vim/gvim/)
        - bash
        - zsh
        - fzf
        - tmux
        - vim-gtk3
        - git
        - curl

    - name: Install yt-dlp
      ansible.builtin.apt:
        name: yt-dlp
        default_release: trixie-backports
        state: latest
