---
- hosts: all
  connection: local
  sudo: yes
  roles:
    - ansible_dep
    - {role: debian_sid, when: "{{ ansible_distribution == 'Debian' }}"}
    - apt_upgrade
    - user
    - base
    - build_dep
    - python
    - docker
    - netsec
      #- docgen
    - browsers

- hosts: endgames
  connection: local
  sudo: yes
  roles:
    - endgame
