---
- hosts: all
  connection: local
  sudo: yes
  roles:
    - ansible_dep
    - {role: debian_sid, when: "{{ ansible_distribution == 'Debian' }}"}
    - apt_upgrade
    - user
    - base
    - build_dep
    - python
    - docker
    - netsec
      #- docgen
    - util
    - {role: gui_util, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: browsers, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: i3, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: terminal, when: "{{ 'DISPLAY' in ansible_env }}"}

- hosts: endgames
  connection: local
  sudo: yes
  roles:
    - endgame

- hosts: argon
  connection: local
  sudo: yes
  roles:
    - lenovo_x1c
