---
- hosts: all
  sudo: yes
  roles:
      #- secrets
    - {role: ansible_dep, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - {role: debian_sid, when: "{{ ansible_distribution == 'Debian' }}"}
    - {role: apt_upgrade, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - user
    - base
    - build_dep
    - python
    - nodejs
    - java
    - devops
    - os-docker
    - netsec
      #- docgen
    - util
    - power
      #- pihole
    - {role: virt, when: "{{ ansible_virtualization_role == 'host' }}"}
    - {role: gui_util, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: browsers, when: "{{ 'DISPLAY' in ansible_env }}"}
    #    - {role: autorandr, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: hackfont, when: "{{ 'DISPLAY' in ansible_env }}"}
    #      #- {role: arbtt, when: "{{ 'DISPLAY' in ansible_env }}"}
    #    - {role: autostart, when: "{{ 'DISPLAY' in ansible_env }}"}

- hosts: ui
  sudo: yes
  roles:
    - {role: gnome, when: "{{ 'DISPLAY' in ansible_env }}"}

- hosts: argon
  sudo: yes
  roles:
    - {role: openbox, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: xfceterminal, when: "{{ 'DISPLAY' in ansible_env }}"}

- hosts: vagrant
  sudo: yes
  roles:
    - swapfile
