---
- hosts: all
  sudo: yes
  roles:
      #- secrets
    - {role: ansible_dep, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - {role: debian_sid, when: "{{ ansible_distribution == 'Debian' }}"}
    - {role: apt_upgrade, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - user
    - base
    - build_dep
    - python
    - docker
    - netsec
      #- docgen
    - util
    - {role: virt, when: "{{ ansible_virtualization_role == 'host' }}"}
    - {role: gui_util, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: browsers, when: "{{ 'DISPLAY' in ansible_env }}"}
    - {role: openbox, when: "{{ 'DISPLAY' in ansible_env }}"}
    #- {role: terminal, when: "{{ 'DISPLAY' in ansible_env }}"}

- hosts: endgame
  sudo: yes
  roles:
    - endgame

- hosts: argon
  sudo: yes
  roles:
    - android
    - lenovo_x1c

- hosts: vagrant
  sudo: yes
  roles:
    - swapfile
