---
- hosts: all
  roles:
    - ansible_dep
    - base

- hosts: chlorine # I _think_ this is my current pc. too lazy to boot and figure out
  become: yes
  roles:
    - openbox
    - nvm

- hosts: 005465.local # work mac
  become: no
  tasks:
    - homebrew_cask: name={{ item }}
      with_items:
        #- google-chrome # preinstalled
        #- firefox
        - iterm2
        #- bettertouchtool
        - meld
        - google-cloud-sdk
        - dbeaver-community
        - inkscape
        - gimp
        #- virtualbox
    - homebrew: name={{ item }}
      with_items:
        - nvm # probably just use nvm role tho?
        - socat
        - htop
        - httpie
        - jq
        - qgis
        - gdal
        - tippecanoe
    #- name: install ntfy
    #  become: yes
    #  community.general.pipx:
    #    name: ntfy
