---
- hosts: all
  become: yes
  roles:
    - ansible_dep
    - base

- hosts: ui,argon
  become: yes
  roles:
    - gnome
    - build_dep
    - python
    - nodejs
    - java
    - devops
    - os-docker
    - portainer
    - netsec
      #- virt - wtf borked on 18.04?
    - gui_util
    - browsers
    - util
    - power
    - git-repo
    - emoji
    - signal
    - qownnotes
    - geo
  tasks:
    - package: name={{item}}
      with_items:
        - fonts-hack-otf
        - bats
    - apt: deb='https://prerelease.keybase.io/keybase_amd64.deb'

- hosts: ui
  become: yes
  roles:
    - "jupyter-notebook"
    - peek
    - flyway
    - uihostname
  tasks:
    - package: name={{item}}
      with_items:
        - graphviz
        - gufw
        - tree
        - gradle
    - apt: deb='https://downloads.slack-edge.com/linux_releases/slack-desktop-3.2.1-amd64.deb'

- hosts: argon
  become: yes
  tasks:
    - package: name={{item}}
      with_items:
        - libgdal-dev
        - calibre

- hosts: vagrant
  become: yes
  roles:
    - swapfile

- hosts: penguin #chrome os linux container
  become: yes
  tasks:
    - package: name={{item}}
      with_items:
        - firefox-esr
        - keepassx
        - xclip

- hosts: MacBook-Pro.localdomain # work mac
  become: no
  roles:
    - nodejs
  tasks:
    - homebrew_cask: name={{ item }}
      with_items:
        - google-chrome
        - firefox
        - iterm2
        - virtualbox
        - keepassxc
        - xquartz
        - vagrant
