---
- hosts: all
  become: yes
  roles:
    - {role: ansible_dep, when: "ansible_distribution in ('Ubuntu', 'Debian')"}
    - {role: debian_sid, when: "ansible_distribution == 'Debian'"}
      #- {role: apt_upgrade, when: "ansible_distribution in ('Ubuntu', 'Debian')"}
    - base

- hosts: ui,argon
  become: yes
  roles:
    - {role: pkg, pkg: gir1.2-gtop-2.0}  # for sysmon gnome panel extension
    - {role: pkg, pkg: libgtop2-dev}  # for sysmon gnome panel extension
    - {role: pkg, pkg: fonts-hack-otf}
    - {role: pkg, pkg: bats}
    - gnome
    - build_dep
    - python
    - nodejs
    - java
    - devops
    - os-docker
    - portainer
    - netsec
    - virt
    - gui_util
    - browsers
    - util
    - power
    - hub
    - emoji

- hosts: ui
  become: yes
  roles:
    - "jupyter-notebook"
    - {role: pkg, pkg: graphviz}
    - {role: pkg, pkg: gufw}
    - {role: pkg, pkg: tree}
    - peek
    - flyway
    - uihostname

- hosts: argon
  become: yes
  roles:
    - {role: pkg, pkg: libgdal-dev }
    - {role: pkg, pkg: calibre }

- hosts: vagrant
  become: yes
  roles:
    - swapfile


# old roles
      #- docgen
      #- pihole
    #    - {role: autorandr, when: "'DISPLAY' in ansible_env"}
    #      #- {role: arbtt, when: "'DISPLAY' in ansible_env"}
    #    - {role: autostart, when: "'DISPLAY' in ansible_env"}
      #- secrets
      #- user
