---
- hosts: all
  become: yes
  roles:
    - {role: ansible_dep, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - {role: debian_sid, when: "{{ ansible_distribution == 'Debian' }}"}
    - {role: apt_upgrade, when: "{{ ansible_distribution in ('Ubuntu', 'Debian') }}"}
    - base

- hosts: ui
  become: yes
  roles:
    - {role: pkg, pkg: graphviz}
    - {role: pkg, pkg: tree}
    - {role: pkg, pkg: gir1.2-gtop-2.0}  # for sysmon gnome panel extension
    - {role: pkg, pkg: libgtop2-dev}  # for sysmon gnome panel extension
    - peek
    - flyway
    - portainer
    - "jupyter-notebook"
    - uihostname
    - gnome
    - build_dep
    - python
    - nodejs
    - java
    - devops
    - os-docker
    - netsec
    - virt
    - gui_util
    - browsers
    - util
    - power
    - {role: pkg, pkg: fonts-hack-otf}

- hosts: argon
  become: yes
  roles:
    - gnome
    - {role: pkg, pkg: gir1.2-gtop-2.0 } # needed for gnome shell sysmon extension
    - {role: pkg, pkg: libgtop2-dev } # needed for gnome shell sysmon extension
    - {role: pkg, pkg: arc-theme }
    - {role: pkg, pkg: libgdal-dev }
    - {role: pkg, pkg: calibre }
    - portainer
    - build_dep
    - python
    - nodejs
    - java
    - devops
    - os-docker
    - netsec
    - virt
    - gui_util
    - browsers
    - util
    - power
    - {role: pkg, pkg: fonts-hack-otf}

- hosts: vagrant
  become: yes
  roles:
    - swapfile


# old roles
      #- docgen
      #- pihole
    #    - {role: autorandr, when: "{{ 'DISPLAY' in ansible_env }}"}
    #      #- {role: arbtt, when: "{{ 'DISPLAY' in ansible_env }}"}
    #    - {role: autostart, when: "{{ 'DISPLAY' in ansible_env }}"}
      #- secrets
      #- user
