- name: Create user
  user:
    name: "{{ user }}"
    comment: "{{ full_name }}"
    shell: /bin/bash
    groups: adm,cdrom,sudo,dip,plugdev
    append: yes
    update_password: on_create
    password: "{{ hashed_unix_password }}"

- name: Lock down root user
  user: name=root password="!"
