- name: Install AWS CLI
  pip: name=awscli

- name: Add Heroku release key for package verification
  apt_key: url=https://toolbelt.heroku.com/apt/release.key state=present

- name: Add Heroku APT repository
  apt_repository: repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present

- name: Install Heroku toolbelt
  apt: name=heroku-toolbelt

- name: Install psql
  apt: name=postgresql-client-common
