- name: Netdata
  docker_compose:
    project_name: netdata
    definition:
      version: '3'
      services:
        netdata:
          image: netdata/netdata
          container_name: netdata
          pid: host
          network_mode: host
          restart: unless-stopped
          cap_add:
            - SYS_PTRACE
            - SYS_ADMIN
          security_opt:
            - apparmor:unconfined
          volumes:
            - config:/etc/netdata
            - lib:/var/lib/netdata
            - cache:/var/cache/netdata
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
      volumes:
        config:
        lib:
        cache:
