- name: Install AutomaticRuleBasedTimeTracker dependencies
  package: name=cabal-install


- name: install other arbtt deps (deb)
  apt: pkg=arbtt state=build-dep
  when: "ansible_distribution in ('Debian', 'Ubuntu')"

    # TODO
  #- name: install other arbtt deps (yum)
  #  yum: pkg=arbtt state=build-deps
  #  when: ansible_distribution in ('CentOS', 'RedHat')
  #- name: install other arbtt deps (dnf)
  #  dnf: pkg=arbtt state=build-deps
  #  when: ansible_distribution in ('Fedora')

- name: update cabal cache
  become_user: "{{user}}"
  command: cabal update
  args:
    creates: ~/.cabal
- name: Install AutomaticRuleBasedTimeTracker
  become_user: "{{user}}"
  command: cabal install arbtt
  args:
    creates: ~/.cabal/bin/arbtt-capture

- name: ensure AutomaticRuleBasedTimeTracker config dir
  become_user: "{{user}}"
  file: path=~/.arbtt state=directory 

- name: Install AutomaticRuleBasedTimeTracker config
  become_user: "{{user}}"
  template: src=categorize.cfg.j2 dest=~/.arbtt/categorize.cfg
