#- name: ensure ~/.config exits
#  file: path=~/.config state=directory
#  become: no
- name: Install dotfiles
  become: no
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - zshrc
    - vimrc
    - gitignore
    - gitconfig
    - inputrc
    - tmux.conf
