- name: Add Signal release key for package verification
  apt_key: url=https://updates.signal.org/desktop/apt/keys.asc state=present

- name: Add Signal APT repository
  apt_repository: repo="deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" state=present

- name: Install Signal
  apt: name=signal-desktop
