# vim: tw=0

# do nothing for noninteractive environments
#[ -z "$PS1" ] && return
[[ $- != *i* ]] && return


###choose editor
if type -P vim &> /dev/null; then
    export EDITOR=vim
elif type -P vi &> /dev/null; then
    export EDITOR=vi
else
    echo 'Vi/Vim not found, EDITOR not set'
fi

###choose pager
if type -P less &> /dev/null; then
    export PAGER=less
else
    export PAGER=more
fi

#### Vi mode & emacs-style clear
set -o vi
bind -m vi-insert "\C-l":clear-screen

#### bash4 ** support
bash --version | grep 'version 4' && shopt -s globstar

# bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi


#for ls:
type -p dircolors > /dev/null && eval $(dircolors -b)


#date utilities
alias today='date +%F'
alias now="date +%FT%T"

#.env utility
alias dotenv='eval $(sed -e "s/^/export /" .env|tr "\n" ";")'

#default behaviours
alias grep='grep --color=auto'
alias df='df -h'
if ls --version 2> /dev/null | grep GNU > /dev/null; then
    alias ls='ls --indicator-style=slash --human-readable --ignore-backups --color=auto --time-style=long-iso'
else
    alias ls='ls -p -h -G'
fi

#common mistakes
alias cd..='cd ..'

#short cuts
alias ll='ls -l'
alias la='ls -la'

## docker-compose shortcuts
function dc {
  docker compose "$@"
}
function dcr {
    dc run --rm "$@"
}

PATH=$PATH:~/.local/bin
export CDPATH=$HOME/code

if [ -f ~/.bashrc.local_ext ]; then
    . ~/.bashrc.local_ext
fi

if [ -f ~/.bashrc.$HOSTNAME ]; then
    . ~/.bashrc.$HOSTNAME
fi

if [ -f /usr/bin/virtualenvwrapper.sh ]; then
    . /usr/bin/virtualenvwrapper.sh
fi

if [ -f ${XDG_CONFIG_HOME}/nvm/nvm.sh ]; then
    . ${XDG_CONFIG_HOME}/nvm/nvm.sh
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi
if [ -f ~/.nvm/nvm.sh ]; then
    . ~/.nvm/nvm.sh
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi
if [ -f /opt/homebrew/opt/nvm/nvm.sh ]; then
    . /opt/homebrew/opt/nvm/nvm.sh
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi
if [ -f "$HOME/.cargo/env" ]; then
    . "$HOME/.cargo/env"
fi

HISTSIZE=9000
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignorespace:ignoredups


function dschep_prompt_command {
    PROMPT_ERROR=$?
    if [ "$PROMPT_ERROR" -ne "0" ]; then
        PROMPT_ERROR=" $PROMPT_ERROR"
    else
        PROMPT_ERROR=
    fi
    echo -ne "\033]0;$USER@$HOSTNAME:${PWD/#$HOME/\~}\007" # set terminal title
    PROMPT_BRANCH="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')" 
    if ! [ "$PROMPT_BRANCH" == "" ]; then
        PROMPT_BRANCH=" $PROMPT_BRANCH"
        if !  git status 2>&1| grep -e "modified:" -e  "Your branch is ahead of" -e "new file:"  -e "rename:" -e "deleted:" &> /dev/null; then
            PROMPT_BRANCH_COLOR=$(tput setaf 2)
        else
            PROMPT_BRANCH_COLOR=$(tput setaf 5)
        fi
    fi
}
if ! [ "$SSH_CONNECTION" == "" ] || [ "$(id -u)" -eq 0 ] || grep docker /proc/1/cgroup &> /dev/null ; then
    PROMPT_USERHOST='\u@\h'
fi
PROMPT_COMMAND='dschep_prompt_command;'
PS1="[\[$(tput sgr0;[ "$(id -u)" -eq 0 ] && tput setaf 1 || tput setaf 2)\]$PROMPT_USERHOST:\[$(tput sgr0;tput bold)\]\W\[$(tput sgr0)\]]\
\[\$PROMPT_BRANCH_COLOR\]\$PROMPT_BRANCH\
\[$(tput setaf 5)\]\$PROMPT_ERROR\
\[$(tput sgr0)\] \[$(tput bold)\]\\$\\[$(tput sgr0)\] "


if type -p direnv &> /dev/null ; then
    eval "$(direnv hook bash)"
fi

## fucking brew
if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

## tmux layouts
function vimux {
    if [[ "$TMUX" != "" ]]; then
        window_name=$(basename $PWD)
        tmux rename-window "$window_name"
        tmux split-window -hb -p 50 vim
        tmux select-pane -t 2
        tmux split-window -v -p 50
        tmux select-pane -t 1
    else
        echo "this function must be run from a shell inside of a tmux session"
    fi
}
function vimuxai {
    if [[ "$TMUX" != "" ]]; then
        window_name=$(basename $PWD)
        tmux rename-window "$window_name"
        tmux split-window -hb -p 33 vim
        tmux select-pane -t 2
        tmux split-window -h -p 50 claude
        tmux select-pane -t 2
        tmux split-window -vb -p 50
        tmux select-pane -t 1
    else
        echo "this function must be run from a shell inside of a tmux session"
    fi
}

# fucking macOS
export BASH_SILENCE_DEPRECATION_WARNING=1

# stupid new docker compose
export COMPOSE_MENU=false
