# vim: tw=0

# do nothing for noninteractive environments
#[ -z "$PS1" ] && return
[[ $- != *i* ]] && return

###choose editor & pager
if type -P vim &> /dev/null; then
    export EDITOR=vim
elif type -P vi &> /dev/null; then
    export EDITOR=vi
else
    echo 'Vi/Vim not found, EDITOR not set'
fi
if type -P less &> /dev/null; then
    export PAGER=less
else
    export PAGER=more
fi

#### Vi mode & emacs-style clear
set -o vi
bind -m vi-insert "\C-l":clear-screen

# local binary dir
PATH=$PATH:~/.local/bin

# cd straight to code
export CDPATH=$HOME/code

# history options
HISTSIZE=9000
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignorespace:ignoredups

# prompt & title
function dschep_prompt_command {
    PROMPT_ERROR=$?
    if [ "$PROMPT_ERROR" -ne "0" ]; then
        PROMPT_ERROR=" $PROMPT_ERROR"
    else
        PROMPT_ERROR=
    fi
    echo -ne "\033]0;$USER@$HOSTNAME:${PWD/#$HOME/\~}\007" # set terminal title
    PROMPT_BRANCH="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')" 
    if ! [ "$PROMPT_BRANCH" == "" ]; then
        PROMPT_BRANCH=" $PROMPT_BRANCH"
        if !  git status 2>&1| grep -e "modified:" -e  "Your branch is ahead of" -e "new file:"  -e "rename:" -e "deleted:" &> /dev/null; then
            PROMPT_BRANCH_COLOR=$(tput setaf 2)
        else
            PROMPT_BRANCH_COLOR=$(tput setaf 5)
        fi
    fi
}
if ! [ "$SSH_CONNECTION" == "" ] || [ "$(id -u)" -eq 0 ] || grep docker /proc/1/cgroup &> /dev/null ; then
    PROMPT_USERHOST='\u@\h'
fi
PROMPT_COMMAND='dschep_prompt_command;'
PS1="[\[$(tput sgr0;[ "$(id -u)" -eq 0 ] && tput setaf 1 || tput setaf 2)\]$PROMPT_USERHOST:\[$(tput sgr0;tput bold)\]\W\[$(tput sgr0)\]]\
\[\$PROMPT_BRANCH_COLOR\]\$PROMPT_BRANCH\
\[$(tput setaf 5)\]\$PROMPT_ERROR\
\[$(tput sgr0)\] \[$(tput bold)\]\\$\\[$(tput sgr0)\] "
