# mouse support
set -g mouse

# use C-a instead of C-b
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# highlight active pane - gruvbox dark colors
set -g window-style 'bg=colour237'
set -g window-active-style 'bg=terminal'
set -g pane-border-lines double
set -g pane-border-status top
set-option -g pane-active-border-style fg=colour172,bg=terminal
set-option -g pane-border-style fg=colour246,bg=colour237
set -g pane-border-format "#[fg=colour239,bg=#{?pane_active,colour172,colour246}] #{?window_zoomed_flag,[,}#{pane_index}#{?window_zoomed_flag,],} #[fg=colour239,bg=#{?pane_active,colour214,colour248}, #{?pane_active,bold,}] #[fg=colour239,bg=#{?pane_active,colour214,colour248}, #{?pane_active,bold,}] #{pane_title} "

# status bar
set -g window-status-current-style bg=black,fg=white

# :vsplit for vim muscle-memory, also to follow directory
set -s command-alias[100] 'vsplit=split-window -h -c "#{pane_current_path}"'
set -s command-alias[101] 'split=split-window -v -c "#{pane_current_path}"'

# and more logical keybindings for splits
bind-key - split-window -c "#{pane_current_path}"
bind-key _ split-window -c "#{pane_current_path}" -f
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key | split-window -h -c "#{pane_current_path}" -f

#####
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
# See https://github.com/christoomey/vim-tmux-navigator/issues/193#issuecomment-354523112
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n C-w if-shell "$is_vim" "send-keys C-w" "switch-client -T VIMWINDOWS"
bind-key -T VIMWINDOWS h select-pane -L
bind-key -T VIMWINDOWS j select-pane -D
bind-key -T VIMWINDOWS k select-pane -U
bind-key -T VIMWINDOWS l select-pane -R
####

# 1-indexed windows & panes!
set -g base-index 1
set -w -g pane-base-index 1

# renumber windows automatically
set -g renumber-windows on

# set window title
set -g set-titles on

# os clipboard
set -s set-clipboard on

# status bar - gruvbox dark colors
set-option -g status "on"
set-option -g status-style bg=colour237,fg=colour223
set-window-option -g window-status-current-format "#[fg=colour239, bg=colour172,bold] #I #[fg=colour239, bg=colour214, bold] #W "
set-window-option -g window-status-format "#[fg=#{?window_bell_flag,colour124,colour235},bg=#{?window_bell_flag,colour235,colour246},nobold] #I #[fg=#{?window_bell_flag,colour167,colour235}, bg=#{?window_bell_flag,colour235,colour248},nobold] #W "
set-option -g status-left "#[fg=colour248, bg=colour241] #S #[fg=colour241, bg=colour237, nobold, noitalics, nounderscore] "
set-option -g status-right "#[fg=colour214, bg=colour239, nobold, noitalics, nounderscore]#{?client_prefix,#[reverse] • #[noreverse],}#[fg=colour241, bg=colour237, nobold, noitalics, nounderscore] #[fg=colour235,bg=colour246,nobold] ⏲ %Y-%m-%d %H:%M #[fg=colour241, bg=colour237, nobold, noitalics, nounderscore] #[fg=colour248, bg=colour241] #h "

# support for vim & claude
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# vi mode copy
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
