# mouse support
set -g mouse

# use C-a instead of C-b
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# highlight active pane
set -g window-style 'bg=colour237'
set -g window-active-style 'bg=terminal'
set -g pane-border-lines double
set -g pane-border-status top

# status bar
set -g window-status-current-style bg=black,fg=white

# :vsplit for vim muscle-memory, also to follow directory
set -s command-alias[100] 'vsplit=split-window -h -c "#{pane_current_path}"'
set -s command-alias[101] 'split=split-window -v -c "#{pane_current_path}"'

#####
# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
# See https://github.com/christoomey/vim-tmux-navigator/issues/193#issuecomment-354523112
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n C-w if-shell "$is_vim" "send-keys C-w" "switch-client -T VIMWINDOWS"
bind-key -T VIMWINDOWS h select-pane -L
bind-key -T VIMWINDOWS j select-pane -D
bind-key -T VIMWINDOWS k select-pane -U
bind-key -T VIMWINDOWS l select-pane -R
####

# 1-indexed windows & panes!
set -g base-index 1
set -w -g pane-base-index 1

# renumber windows automatically
set -g renumber-windows on

# set window title
set -g set-titles on
