set nocompatible
filetype off " turned back on later

"""
""" vundle
"""
let vundleInstalled=0
if !isdirectory(expand("~/.vim/bundle/Vundle.vim/.git"))
    echo "Installing Vundle"
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/Vundle.vim ~/.vim/bundle/Vundle.vim
    let vundleInstalled=1
endif
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'junegunn/fzf' " file mgmt
Plugin 'junegunn/fzf.vim' " file mgmt
Plugin 'morhetz/gruvbox' " pretty colors!
Plugin 'scrooloose/nerdtree' " File browser

" LSP & autocomplete
Plugin 'prabirshrestha/vim-lsp'
Plugin 'mattn/vim-lsp-settings'
Plugin 'prabirshrestha/asyncomplete.vim'
Plugin 'prabirshrestha/asyncomplete-lsp.vim'

" Autoformat
Plugin 'vim-autoformat/vim-autoformat'

" tmux integration
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()

if vundleInstalled == 1
    echo "Installing Vundle plugins"
    echo ""
    PluginInstall
endif


"""
""" Key mappings
"""
" esc-esc in normal mode to clear search highlight
nnoremap <ESC><ESC> :noh<CR>
" esc-esc in terminal mode to switch to normal mode
tnoremap <ESC><ESC> <C-W>N
" bind F2 to toggle paste mode
set pastetoggle=<F2>
" toggle line numberings with F3
nnoremap <F3> :set number!<CR>

"" plugins
" fzf bindings
nnoremap <silent><C-p> :Files<CR>
nnoremap <silent><C-Space> :Buffers<CR>
" vim-tmux-navigator
let g:tmux_navigator_no_mappings = 1
nnoremap <C-w> <nop>
nnoremap <silent><C-w>l :TmuxNavigateRight<cr>
nnoremap <silent><C-w>j :TmuxNavigateDown<cr>
nnoremap <silent><C-w>k :TmuxNavigateUp<cr>
nnoremap <silent><C-w>h :TmuxNavigateLeft<cr>




"""
""" Behaviour
"""
" normal backspace
set backspace=indent,eol,start
" mouse support
if exists('+mouse')
    set mouse=a
endif
if exists('$TMUX')
    set ttymouse=xterm2
endif
" regex magic
set magic
" use incremental search
set incsearch
" quickly move cursor to matching bracket when added
set showmatch


"""
""" Appearance
"""
" 256 colors
set t_Co=256
" Syntax hilighting
syn on
" hilight search results
set hlsearch
" set terminal title
set title
" always show status line
set laststatus=2
" gruvbox colorscheme
set background=dark
colors gruvbox
let g:gruvbox_contrast_light='light'
" highlight current line
set cursorline
" highlight last column
if exists('+colorcolumn')
  set colorcolumn=+1
endif
" but use terminal background (for active pane higlighting in tmux)
highlight Normal ctermbg=NONE guibg=NONE
" and dim inactive splits to match tmux pane highlighting
hi DimNormal ctermbg=237
augroup ActiveWin | au!
    au WinEnter * setl wincolor=
    au WinLeave * setl wincolor=DimNormal
augroup END


"""
""" File type Options
"""
" full file type detection
filetype plugin indent on
" use real tabs for makefiles
autocmd BufNewFile,BufReadPost Makefile,makefile,*.mk setlocal noexpandtab
" use 2 spaces for tabs in javascript/typescript/yaml
autocmd BufNewFile,BufReadPost *.js setlocal tabstop=2 shiftwidth=2
autocmd BufNewFile,BufReadPost *.ts setlocal tabstop=2 shiftwidth=2
autocmd BufNewFile,BufReadPost *.yml setlocal tabstop=2 shiftwidth=2
autocmd BufNewFile,BufReadPost *.yaml setlocal tabstop=2 shiftwidth=2
" use 2 spaces for tabs in yaml
autocmd BufNewFile,BufReadPost *.yaml,*.yml setlocal tabstop=2 shiftwidth=2
" detect json files
autocmd BufNewFile,BufReadPost *.json setlocal ft=json
" detect markdown files
autocmd BufNewFile,BufReadPost *.md setlocal filetype=markdown
" use modelines
set modeline
" JSX in JS files
let g:jsx_ext_required = 0
" more syntax for python
let python_highlight_all = 1


"""
""" Text style options
"""
" 4 space tabs 
set tabstop=4
set shiftwidth=4
set expandtab
" disable mixing spaces and \t
set softtabstop=0
" set wrapping text width
set textwidth=99


"""
""" Misc.
"""
set encoding=utf-8
" add custom spellings
if exists('+spellfile')
    set spellfile=~/.vim/spellfile.add
endif
" spell check
set spell spelloptions=camel
hi SpellBad cterm=underline
syn spell toplevel


"""
""" ENV customization
"""
set cdpath=,~/code
