# vim: tw=0

# do nothing for noninteractive environments
[[ -o interactive ]] || return

# util func
function _has_command {
    (( $+commands[$1] ))
}

### choose editor & pager
if _has_command vim; then
    export EDITOR=vim
elif _has_command vi; then
    export EDITOR=vi
else
    echo 'Vi/Vim not found, EDITOR not set'
fi
if _has_command less; then
    export PAGER=less
else
    export PAGER=more
fi

# Vi mode & emacs-style clear/history-search using fzf
bindkey -v
bindkey -M viins '^L' clear-screen

# zsh completion
fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
    compinit
else
    compinit -C
fi

# colors for ls & completion:
if _has_command dircolors; then
    eval "$(dircolors -b)"
fi
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# local binary dir
path+=("$HOME/.local/bin")
typeset -U path
export PATH

# cd straight to code
export CDPATH=$HOME/code

# history options
HISTSIZE=9000
SAVEHIST=$HISTSIZE
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
setopt hist_ignore_space
setopt hist_ignore_dups
setopt no_nomatch

# prompt
_dschep_prompt_userhost=''
if [[ -n "$SSH_CONNECTION" || "$EUID" -eq 0 ]] || { [[ -r /proc/1/cgroup ]] && grep -q docker /proc/1/cgroup 2>/dev/null; }; then
    _dschep_prompt_userhost=' %n@%m '
fi
_dschep_prompt_nixshell=''
setopt prompt_subst
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable ALL
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '%K{#b16286}%F{#282828}'
zstyle ':vcs_info:git:*' unstagedstr '%K{#b16286}%F{#282828}'
zstyle ':vcs_info:git:*' formats '%K{#98971a}%F{#282828}%c%u %b %f%k'
zstyle ':vcs_info:git:*' actionformats '%K{#b16286}%F{#282828}%c%u %b|%a %f%k'
function dschep_prompt_command {
    print -Pn "\e]0;%n@%m:%~\a"
    _dschep_prompt_nixshell=''
    if [[ -n "$IN_NIX_SHELL" ]]; then
        _dschep_prompt_nixshell='%K{#458588}%F{#282828} ❄ '
    fi
    vcs_info
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd dschep_prompt_command
PROMPT=$'\n%(!.%K{#cc241d}.%K{#98971a})%F{#282828}${_dschep_prompt_userhost}%K{#d79921}%F{#282828} %B%~ ${_dschep_prompt_nixshell}${vcs_info_msg_0_}%F{#282828}%K{#cc241d}%(?.. %? )%f%k\n%B%#%b '

zmodload zsh/mathfunc
## tmux layout
function tmuxl {
    if [[ "$TMUX" == "" ]]; then
        tmux new-session -d
    fi

    tmux rename-window "$(basename $PWD)"

    # save command for primary panel to run it at the end
    local one
    if (( $# > 0 )); then
        one="$1"
        shift
    else
        one="$SHELL"
    fi

    # second pane
    if (( $# > 0 )); then
        tmux split-window -h $1
        shift
    fi

    if (( $# == 1 )); then
        # if there's just a 3rd pane, create it and be done
        tmux split-window $1
    elif (( $# > 0 )); then
        # pane 3 & 4 and the math for subsequent panes
        local middle
        local right
        middle=$(( ceil( ( $# + 1 ) / 2. ) ))
        right=$(( floor( ( $# + 1 ) / 2. ) ))

        tmux split-window -p $(( int( 100 * ( 1 - ( 1 / $middle ) ) ) )) $1
        shift
        middle=$(( $middle - 1 ))

        tmux split-window -h -f -p 33 $1
        shift

        # handle all remaining panes, alternating between adding to left & right
        while (( $# > 0 )); do
            if (( ( $(tmux display-message -p '#{window_panes}') % 2 ) == 0 )); then
                tmux split-window -p $(( int( 100 * ( 1 - ( 1 / $right ) ) ) )) $1
                right=$(( $right - 1 ))
                tmux select-pane -L
            else
                tmux split-window -p $(( int( 100 * ( 1 - ( 1 / $middle ) ) ) )) $1
                middle=$(( $middle - 1 ))
                tmux select-pane -R
            fi
            shift
        done
    fi

    # reselect the first pane
    tmux select-pane -t 1
    tmux send-keys "exec $one" C-m

    if [[ "$TMUX" == "" ]]; then
        tmux attach
    fi
}

# load local extensions to zshrc
if [[ -f ~/.zshrc.local_ext ]]; then
    . ~/.zshrc.local_ext
fi

# Setup shell-integrated software
if _has_command fnm ; then
    eval "$(fnm env --shell zsh)"
fi
if [[ -f "$HOME/.cargo/env" ]]; then
    . "$HOME/.cargo/env"
fi
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
if _has_command direnv ; then
    eval "$(direnv hook zsh)"
fi
if _has_command fzf; then
  eval "$(fzf --zsh)"
  export FZF_DEFAULT_OPTS=$'--color=fg:#ebdbb2,bg:#282828,hl:#fabd2f,fg+:#ebdbb2,bg+:#3c3836
  --color=hl+:#fabd2f,info:#83a598,prompt:#bdae93,pointer:#83a598
  --color=marker:#a8c4b9,spinner:#fabd2f,header:#a89984,border:#504945
  --color=gutter:#3c3836'
else
  bindkey -M viins '^R' history-incremental-search-backward
fi

# date utilities
alias today='date +%F'
alias now="date +%FT%T"

# default behaviors
alias grep='grep --color=auto'
alias df='df -h'
if command ls --version 2> /dev/null | grep GNU > /dev/null; then
    alias ls='ls --indicator-style=slash --human-readable --ignore-backups --color=auto --time-style=long-iso'
else
    alias ls='ls -p -h -G'
fi

#common mistakes
alias cd..='cd ..'

#short cuts
alias ll='ls -l'
alias la='ls -la'

## docker-compose shortcuts
function dc {
  docker compose "$@"
}
function dcr {
    dc run --rm "$@"
}

# stupid new docker compose
export COMPOSE_MENU=false
