# vim: tw=0

# do nothing for noninteractive environments
[[ -o interactive ]] || return

function _has_command {
    (( $+commands[$1] ))
}

###choose editor
if _has_command vim; then
    export EDITOR=vim
elif _has_command vi; then
    export EDITOR=vi
else
    echo 'Vi/Vim not found, EDITOR not set'
fi

###choose pager
if _has_command less; then
    export PAGER=less
else
    export PAGER=more
fi

#### Vi mode & emacs-style clear/history-search
bindkey -v
bindkey -M viins '^L' clear-screen
bindkey -M viins '^R' history-incremental-search-backward

#### zsh completion
autoload -Uz compinit
compinit

#for ls & completion:
if _has_command dircolors; then
    eval "$(dircolors -b)"
fi
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

#date utilities
alias today='date +%F'
alias now="date +%FT%T"

#.env utility
alias dotenv='eval $(sed -e "s/^/export /" .env|tr "\n" ";")'

#default behaviours
alias grep='grep --color=auto'
alias df='df -h'
if command ls --version 2> /dev/null | grep GNU > /dev/null; then
    alias ls='ls --indicator-style=slash --human-readable --ignore-backups --color=auto --time-style=long-iso'
else
    alias ls='ls -p -h -G'
fi

#common mistakes
alias cd..='cd ..'

#short cuts
alias ll='ls -l'
alias la='ls -la'

## docker-compose shortcuts
function dc {
  docker compose "$@"
}
function dcr {
    dc run --rm "$@"
}

path+=("$HOME/.local/bin")
typeset -U path
export PATH
export CDPATH=$HOME/code

if [[ -f ~/.zshrc.local_ext ]]; then
    . ~/.zshrc.local_ext
fi

_dschep_host=${HOSTNAME:-$HOST}
if [[ -f "$HOME/.zshrc.$_dschep_host" ]]; then
    . "$HOME/.zshrc.$_dschep_host"
fi
unset _dschep_host

if [[ -f /usr/bin/virtualenvwrapper.sh ]]; then
    . /usr/bin/virtualenvwrapper.sh
fi

_dschep_bashcompinit_loaded=0
function dschep_load_bash_completion {
    local completion_file="$1"

    [[ -s "$completion_file" ]] || return

    if [[ "$_dschep_bashcompinit_loaded" -eq 0 ]]; then
        autoload -Uz bashcompinit
        bashcompinit
        _dschep_bashcompinit_loaded=1
    fi

    . "$completion_file"
}

function dschep_source_nvm {
    local nvm_sh="$1"

    [[ -f "$nvm_sh" ]] || return

    . "$nvm_sh"
    dschep_load_bash_completion "$NVM_DIR/bash_completion"
}

if [[ -n "$XDG_CONFIG_HOME" ]]; then
    dschep_source_nvm "$XDG_CONFIG_HOME/nvm/nvm.sh"
fi
dschep_source_nvm "$HOME/.nvm/nvm.sh"
dschep_source_nvm "/usr/share/nvm/nvm.sh"
dschep_source_nvm "/opt/homebrew/opt/nvm/nvm.sh"

if [[ -f "$HOME/.cargo/env" ]]; then
    . "$HOME/.cargo/env"
fi

HISTSIZE=9000
SAVEHIST=$HISTSIZE
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
setopt hist_ignore_space
setopt hist_ignore_dups
setopt no_nomatch

_dschep_prompt_userhost=''
if [[ -n "$SSH_CONNECTION" || "$EUID" -eq 0 ]] || { [[ -r /proc/1/cgroup ]] && grep -q docker /proc/1/cgroup 2>/dev/null; }; then
    _dschep_prompt_userhost='%n@%m'
fi

setopt prompt_subst

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '%F{magenta}'
zstyle ':vcs_info:git:*' unstagedstr '%F{magenta}'
zstyle ':vcs_info:git:*' formats ' %F{green}%c%u%b%f'
zstyle ':vcs_info:git:*' actionformats ' %F{magenta}%b|%a%f'

function dschep_prompt_command {
    print -Pn "\e]0;%n@%m:%~\a"
    vcs_info
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd dschep_prompt_command

PROMPT='[%(!.%F{red}.%F{green})${_dschep_prompt_userhost}:%f%B%1~%b]${vcs_info_msg_0_}%F{magenta}%(?.. %?)%f %B%#%b '

if _has_command direnv ; then
    eval "$(direnv hook zsh)"
fi

## fucking brew
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

## tmux layout
function vimux {
    if [[ "$TMUX" != "" ]]; then
        local ratio
        local window_name
        ratio=50
        if [[ "$1" != "" ]]; then
            ratio=33
        fi
        window_name=$(basename $PWD)
        tmux rename-window "$window_name"
        tmux split-window -hb -p $ratio vim
        tmux select-pane -t 2
        if [[ "$1" != "" ]]; then
            tmux split-window -h -p 50 $1
        fi
        tmux select-pane -t 2
        tmux split-window -v -p 50
        tmux select-pane -t 1
    else
        echo "this function must be run from a shell inside of a tmux session"
    fi
}

# stupid new docker compose
export COMPOSE_MENU=false
