- name: autostart scripts
  sudo_user: "{{ user }}"
  copy: src=xsessionrc dest=~/.autostart

- file: path=~/.config/autostart state=directory
- name: autostart .desktop file
  sudo_user: "{{ user }}"
  copy: src=autostart.desktop dest=~/.config/autostart/autostart.desktop
