# mouse support
set -g mouse

# use C-a instead of C-b
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# use prefix hjkl for split mvmt
unbind l
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R
