- name: KeepassXC repo
  apt_repository: repo="ppa:phoerious/keepassxc"

- name: remove KeepassX
  apt: state=absent pkg=keepassx

- name: Install GUI tools
  package: name={{ item }}
  with_items:
    - keepassxc
      #- vim-gnome
    - gitk
    - git-gui
    - meld
    - gimp
    - inkscape
    - "{{ 'mplayer' if ansible_distribution in ('Debian', 'Ubuntu') else 'kmplayer' }}"
    - ubuntu-restricted-extras
      #- ssh-askpass-gnome
    - xclip
    - guake
    - vim-gtk3
