- name: Install GUI tools
  package: name={{ item }}
  with_items:
    - keepassx
      #- vim-gnome
    - gitk
    - git-gui
    - meld
    - gimp
    - inkscape
    - "{{ 'mplayer' if ansible_distribution in ('Debian', 'Ubuntu') else 'kmplayer' }}"
    - ubuntu-restricted-extras
      #- ssh-askpass-gnome
    - xclip
    - guake
    - vim-gtk3
