- name: Install GUI tools
  package: name={{ item }}
  with_items:
    - keepassx
      #- vim-gnome
    - gitk
    - git-gui
    - meld
    - gimp
    - inkscape
    - "{{ 'mplayer' if ansible_distribution in ('Debian', 'Ubuntu') else 'kmplayer' }}"
      #- ssh-askpass-gnome

- name: install imgur screenshot script
  get_url: url=https://raw.githubusercontent.com/dschep/img/master/img.sh dest=/usr/bin/img.sh mode=755
