- name: Install various netsec Tools
  package: name={{ item }}
  with_items:
    - nmap
    - "{{ 'openssl-devel' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'libssl-dev' }}"
    - libffi-{{ 'devel' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'dev' }}
    - dsniff

- name: Install mitmproxy
  pip: name=mitmproxy
