- name: Allocate swap file
  command: fallocate -l {{ swap_size }} {{ swap_file }}
  args:
    creates: '{{ swap_file }}'
  register: swapfile_created

- name: Enforce permissions
  file:
    path: '{{ swap_file  }}'
    state: 'file'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: Initialize swap file
  command: mkswap {{ swap_file }}
  register: swapfile_initialized
  with_items: swapfile_register_allocation.results
  when: swapfile_created|changed

- name: Enable swap files
  command: swapon {{ swap_file }}
  with_items: swapfile_register_allocation.results
  when: swapfile_initialized|changed

- name: Manage swap file in /etc/fstab
  mount:
    src: '{{ swap_file }}'
    name:   'none'
    fstype: 'swap'
    opts:   'defaults'
    dump:   '0'
    passno: '0'
    state:  'present'
