- name: Install i3 & desktop env parts
  apt: pkg={{ item }}
  with_items:
   - i3
   - network-manager-gnome
   #- xfce4-notifyd
   - xfce4-power-manager
   - blueman
   - volumeicon-alsa
   - pavucontrol
   - xscreensaver

- name: Purge dunst
  apt: pkg=dunst state=absent

- name: Install i3 dotfiles
  become_user: "{{ user }}"
  copy: src={{ item }} dest=~/.{{ item }}
  with_items:
    - i3/
    - i3status.conf
