- name: Install custom pushover util
  copy: src=pushover dest=/usr/bin/pushover mode=755

- name: Link custom pushover notify-done util
  file: src=/usr/bin/pushover dest=/usr/bin/notify-done state=link

- name: Install CLI tools
  apt: pkg={{ item }}
  with_items:
    # basic file tools
    - dos2unix
    - inotify-tools
    # curl. duh
    - curl
    # compression tools
    - unrar-free
    - p7zip-full
    - dtrx
    # system tools
    - htop
    - apt-file
    # network
    - ethtool
    # disc encryption
    - encfs
    # search
    - silversearcher-ag

- name: Install GUI tools
  apt: pkg={{ item }}
  with_items:
    - keepassx
    - vim-gnome
    - gitk
    - git-gui
    - meld
    - gimp
    - inkscape
    - mplayer


- name: install imgur screenshot script
  get_url: url=https://raw.githubusercontent.com/dschep/img/master/img.sh dest=/usr/bin/img.sh mode=755
