- name: Install CLI tools
  package: name={{ item }}
  with_items:
    # basic file tools
    - dos2unix
    - inotify-tools
    - jq
    # HTTP clients
    - wget
    - curl
    - httpie
    # compression tools
    - "{{ 'p7zip' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'p7zip-full' }}"
    # system tools
    - htop
    # network
    - ethtool
    - socat
    # disc encryption
    - encfs
    # search
    - "{{ 'the_silver_searcher' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'silversearcher-ag' }}"
    - python-dbus # needed for ntfy

- name: install glances
  pip: name=glances state=latest

- name: install ntfy
  pip: name="git+https://github.com/dschep/ntfy.git@locked#egg=ntfy"
- name: install jot
  pip: name=jot-notes executable=pip state=latest

- pip: name=horseshit state=latest
- name: Install horseshit config
  become_user: "{{ user }}"
  copy: src=horseshits dest=~/.config/horseshits

- name: install apt-file
  apt: name=apt-file
  when: ansible_distribution in ('Debian', 'Ubuntu')
