- name: Install common build deps
  package: name={{ item }}
  with_items:
    - libxml2-{{ 'devel' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'dev' }}
    - "{{ 'libxslt-devel' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'libxslt1-dev' }}"
    - libjpeg-{{ 'devel' if ansible_distribution in ('CentOS', 'RedHat', 'Fedora') else 'dev' }}
