- name: Portainer
  docker_compose:
    project_name: portainer
    definition:
      version: '3'
      services:
        portainer:
          image: "portainer/portainer-ce:latest"
          container_name: portainer
          restart: unless-stopped
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "data:/data"
          ports:
            - "9443:9443"
      volumes:
        data:
