- name: Install openbox and utils used in config
  package: name={{ item }}
  with_items:
    - openbox
    - dmenu
    - xbacklight
    - xcompmgr
- file: path=~/.config/openbox state=directory
  sudo_user: "{{ user }}"
- name: Install openbox dotfiles
  sudo_user: "{{ user }}"
  copy: src=rc.xml dest=~/.config/openbox/rc.xml
