- name: Install openbox and utils used in config
  package: name={{ item }}
  with_items:
    - openbox
    - dmenu
    - xbacklight
    - xcompmgr
- file: path=~/.config/openbox state=directory
  become_user: "{{ user }}"
- name: Install openbox dotfiles
  become_user: "{{ user }}"
  copy: src=rc.xml dest=~/.config/openbox/rc.xml
- name: Install openbox dotfiles for lubuntu
  become_user: "{{ user }}"
  copy: src=rc.xml dest=~/.config/openbox/lubuntu-rc.xml
