- name: Install openbox and utils used in config
  package: name={{ item }}
  with_items:
    - openbox
    - dmenu
- file: path=~/.config/openbox state=directory
  become: no
- name: Install openbox dotfiles
  become: no
  copy: src=rc.xml dest=~/.config/openbox/rc.xml
- name: Install openbox dotfiles for lubuntu
  become: no
  copy: src=rc.xml dest=~/.config/openbox/lubuntu-rc.xml
