- name: Install openbox and utils used in config
  package: name={{ item }}
  with_items:
    - openbox
    - dmenu
    - xbacklight
    - xcompmgr
- file: path=~/.config/openbox state=directory
  become_user: "{{ user }}"
- name: Install openbox dotfiles
  become_user: "{{ user }}"
  copy: src=rc.xml dest=~/.config/openbox/rc.xml
- name: Install openbox dotfiles for lubuntu
  become_user: "{{ user }}"
  copy: src=rc.xml dest=~/.config/openbox/lxqt-rc.xml

  #- name: qterminal config
  #  become_user: "{{ user }}"
  #  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  #  with_items:
  #    - config/qterminal.org/qterminal.ini
  #    - config/qterminal.org/color-schemes/Gruvbox_dark.colorscheme
