---
- name: Install Nix (multi-user)
  become: yes
  ansible.builtin.shell: |
    if [ ! -d /nix ]; then curl -fsSL https://nixos.org/nix/install | sh -s -- --daemon; fi
  args:
    creates: /nix/var/nix/profiles/default/bin/nix-env
