- name: Add Docker repository key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repository
  apt_repository: repo="deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" update_cache=yes

- name: Install Docker
  package: name={{ item }}
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    # python deps for ansible
    - python3-docker
    - docker-compose
