- name: Install Base tools
  apt: pkg={{ item }}
  with_items:
    - screen
    - vim
    - git

- name: Install Base dotfiles
  sudo_user: "{{ user }}"
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - bash_logout
    - liquidprompt/
    - vimrc
    - gitignore
    - inputrc
    - screenrc

- name: Install gitconfig
  sudo_user: "{{ user }}"
  template: src=gitconfig dest=~/.gitconfig
