- name: Install Base tools (linux)
  package: name={{ item }}
  become: yes
  with_items:
    - screen
    - vim
    - git
    - direnv
  when: ansible_distribution != 'MacOSX'
- name: Install Base tools (mac)
  package: name={{ item }}
  with_items:
    - bash
    - direnv
  become: no
  when: ansible_distribution == 'MacOSX'
- file: path=~/.config state=directory
  become: no
- file: path=~/.config/nvim state=directory
  become: no
- name: Install Base dotfiles
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bash_profile
    - bash_logout
    - vimrc
    - gitignore
    - inputrc
    - screenrc
    - serverlessrc
    - config/nvim/init.vim


- name: Install gitconfig
  template: src=gitconfig dest=~/.gitconfig
