- name: Install Base tools
  package: name={{ item }}
  with_items:
    - screen
    - vim
    - git
    - neovim

- name: Install Base dotfiles
  become_user: "{{ user }}"
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bashrc.ui
    - bash_profile
    - bash_logout
    - liquidprompt/
    - vimrc
    - gitignore
    - inputrc
    - screenrc
    - serverlessrc
    - config/neovim/init.vim

- name: Install gitconfig
  become_user: "{{ user }}"
  template: src=gitconfig dest=~/.gitconfig
