- name: Install Base tools (linux)
  package: name={{ item }}
  with_items:
    - screen
    - vim
    - git
    - neovim
    - direnv
  when: ansible_distribution != 'MacOSX'
- name: Install Base tools (mac)
  package: name={{ item }}
  with_items:
    - neovim
    - direnv
  become: no
  when: ansible_distribution == 'MacOSX'
- file: path=~/.config state=directory
  become: no
- file: path=~/.config/nvim state=directory
  become: no
- name: Install Base dotfiles
  become_user: "{{ user }}"
  copy: src=dotfiles/{{ item }} dest=~/.{{ item }}
  with_items:
    - bashrc
    - bashrc.ui
    - bash_profile
    - bash_logout
    - vimrc
    - gitignore
    - inputrc
    - screenrc
    - serverlessrc
    - config/nvim/init.vim

- name: Install nvim wrapper
  copy: src=nvim-terminal-edit.py dest=/usr/local/bin/nvim-terminal-edit.py mode=755

- name: Install gitconfig
  become_user: "{{ user }}"
  template: src=gitconfig dest=~/.gitconfig
