- name: Install Base tools
  package: name={{ item }}
  become: yes
  with_items:
    - bash
    - zsh
    - fzf
    - tmux
    - vim
    - git
    - direnv
  when: ansible_facts['distribution'] != 'MacOSX'
- name: Install Base tools (mac)
  package: name={{ item }}
  become: no
  with_items:
    - bash
    - fzf
    - tmux
    - vim
    - git
    - direnv
  when: ansible_facts['distribution'] == 'MacOSX'
