#!/bin/bash

# Easily setup up a machine to my liking using ansible. Bootstrap
# should work on recent Ubuntu, Debian, Fedora, Arch, Alpine, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# arguments are passed to ansible-pull (eg: a playbook name)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- dotfiles.yml

set -euo pipefail


# determine package manager
PKG_MGR=()
if [[ "$(uname)" = Darwin ]]; then
    PKG_MGR=("brew" "install")
    if ! type -p brew &> /dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
else
    if [ "$(id -u)" -ne 0 ]; then
        PKG_MGR=("sudo")
    fi
    if type -p apt &> /dev/null; then
        PKG_MGR+=("apt" "install" "-y")
    elif type -p apt-get &> /dev/null; then
        PKG_MGR+=("apt-get" "install" "-y")
    elif type -p dnf &> /dev/null; then
        PKG_MGR+=("dnf" "install" "-y")
    elif type -p yum &> /dev/null; then
        PKG_MGR+=("yum" "install" "-y")
    elif type -p apk &> /dev/null; then
        PKG_MGR+=("apk" "add")
    elif type -p pacman &> /dev/null; then
        PKG_MGR+=("pacman" "-yS" "--noconfirm")
    else
        echo 'No known package manager found' >&2
        exit 1
    fi
fi


# install ansible & git if necessary
if ! type -p ansible &> /dev/null ; then
    "${PKG_MGR[@]}" ansible
fi
if ! type -p git &> /dev/null ; then
    "${PKG_MGR[@]}" git
fi


# run ansible!
if [ "$(id -u)" -ne 0 ]; then
    ansible-pull -U https://github.com/dschep/box -K "$@"
else
    ansible-pull -U https://github.com/dschep/box "$@"
fi


# Easily setup up a machine to my liking using ansible. Bootstrap
# should work on recent Ubuntu, Debian, Fedora, Arch, Alpine, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# arguments are passed to ansible-pull (eg: a playbook name)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- dotfiles.yml
