#!/bin/bash

#
# Easily setup up a machine to my liking using ansible. Bootstrap
# should work on recent Ubuntu, Debian, Fedora, Arch, Alpine, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# arguments are passed to ansible-pull (eg: a playbook name)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- dotfiles.yml

set -euo pipefail


# determine package manager
SUDO=""
PKG=""
if [[ "$(uname)" = Darwin ]]; then
    PKG="brew install"
    if ! $(type -p brew &> /dev/null); then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
else
    if [ "$(id -u)" -ne 0 ]; then
        SUDO="sudo"
    fi
    if $(type -p apt &> /dev/null); then
        PKG="apt install"
    elif $(type -p apt-get &> /dev/null); then
        PKG="apt-get install"
    elif $(type -p dnf &> /dev/null); then
        PKG="dnf install"
    elif $(type -p yum &> /dev/null); then
        PKG="yum install"
    elif $(type -p apk &> /dev/null); then
        PKG="apk add"
    elif $(type -p pacman &> /dev/null); then
        PKG="pacman -yS --noconfirm"
    else
        echo 'No known package manager found' >&2
        exit 1
    fi
fi


# install ansible & git if necessary
if ! type -p ansible &> /dev/null ; then
    $SUDO $PKG -y ansible
fi
if ! type -p git &> /dev/null ; then
    $SUDO $PKG -y git
fi


# run ansible!
if [ "$(id -u)" -ne 0 ]; then
    ansible-pull -U https://github.com/dschep/box -K "$@"
else
    ansible-pull -U https://github.com/dschep/box "$@"
fi


# Easily setup up a machine to my liking using ansible. Bootstrap
# should work on recent Ubuntu, Debian, Fedora, Arch, Alpine, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# arguments are passed to ansible-pull (eg: a playbook name)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- dotfiles.yml
