#!/bin/bash

#
# Easily setup up a machine to my liking using ansible. Should work on
# recent Ubuntu, Debian, Fedora, Arch, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# flags:
# --git-*       Use git+* instead of https, eg: git+ssh git+git or git+http[s]
#
# positional arguments:
# branchname      specify branch to download/checkout (defaults to master)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- --git-ssh test-branch

set -e

PYDEV=""
if [[ "$(uname)" = Darwin ]]; then
    PKG="brew install"
    if ! $(type -p brew &> /dev/null); then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
else
    if $(type -p apt &> /dev/null); then
        PKG="apt install"
        PYDEV="python-dev libssl-dev"
    elif $(type -p apt-get &> /dev/null); then
        PKG="apt-get install"
        PYDEV="python-dev libssl-dev"
    elif $(type -p dnf &> /dev/null); then
        PKG="dnf install"
        PYDEV=python-devel
    elif $(type -p yum &> /dev/null); then
        PKG="yum install"
        PYDEV=python-devel
    elif $(type -p pacman &> /dev/null); then
        PKG="pacman -yS"
    else
        echo 'No known package manager found' >&2
        exit 1
    fi
fi

if [[ $1 == --git-* ]]; then
    type -p git &> /dev/null || sudo $PKG install git
    proto=${1##*-}
    shift
    git clone -b ${1-master} $proto://git@github.com/dschep/box
    cd box
else
    if [ "$(type -P wget)" ]; then
        cmd='wget -qO-'
    elif [ "$(type -P curl)" ]; then
        cmd='curl -sL'
    else
        echo "No download tool found. Install curl or wget."1>&2
    fi
    
    $cmd https://github.com/dschep/box/archive/refs/heads/${1-master}.tar.gz | tar xz
    cd box-${1-master}
fi


if ! type -p ansible-playbook &> /dev/null ; then
    sudo $PKG -y python-pip $PYDEV ansible
fi

ansible-playbook -i $HOSTNAME, site.yml

# Repeating doc at bottom for easy reading when cURLing
# Easily setup up a machine to my liking using ansible. Should work on
# recent Ubuntu, Debian, Fedora, Arch, & MacOS
#
# curl https://dschep.github.io/box/install | bash
# or
# wget -qO- https://dschep.github.io/box/install | bash
#
# flags:
# --git-*       Use git+* instead of https, eg: git+ssh git+git or git+http[s]
#
# positional arguments:
# branchname      specify branch to download/checkout (defaults to master)
#
# Example
# curl https://dschep.github.io/box/install | bash -s -- --git-ssh test-branch
